insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('mpitchers0', 'lpriestner0@tiny.cc', '13oVi9u1gN', 'morph distributed schemas', null, '02/20/1922', 'Genderqueer', '01532', true, false, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('gbride1', 'cjenyns1@meetup.com', '3gL51qlWbl', 'optimize robust solutions', null, '05/06/1947', 'Agender', '735', true, true, false, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('sdrowsfield2', 'sgiacovelli2@about.com', '7DtcamyRUu', 'streamline virtual web-readiness', null, '04/11/1943', 'Genderqueer', '9917', true, false, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('gallinson3', 'bferagh3@eepurl.com', 'U2hetHaRqiQH', 'unleash clicks-and-mortar platforms', null, '01/14/1919', 'n', '64397', true, true, true, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('bwilloughway4', 'abilbery4@acquirethisname.com', 'Yf5q7m', 'iterate back-end channels', null, '06/22/2006', 'm', '2023', false, false, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('ashemwell5', 'eelles5@unesco.org', 'SFYg55', 'transition magnetic infrastructures', null, '10/08/2012', 'Polygender', '36', true, false, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('fscading6', 'nsherrington6@arizona.edu', 'aJyJS5I', 'mesh value-added infrastructures', null, '04/19/1917', 'Bigender', '34', false, false, false, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('mmountcastle7', 'ncamier7@uol.com.br', 'KyhSWT4Ip4gV', 'engineer collaborative users', null, '01/20/1976', 'Genderfluid', '89', true, true, false, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('mplowman8', 'showgego8@psu.edu', '97HEdZhHmt', 'utilize seamless partnerships', null, '09/12/1932', 'Polygender', '335', false, true, false, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('lprozescky9', 'akittow9@1688.com', 'g1yng049V', 'brand interactive partnerships', null, '08/31/1963', 'm', '2', true, true, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('abellinia', 'ayoulla@dropbox.com', 'Sh5JeW9', 'mesh revolutionary applications', null, '08/17/1927', 'm', '34685', false, false, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('cboordb', 'lwanneb@blogtalkradio.com', '7tDRyp8s', 'enable revolutionary systems', null, '12/22/1965', 'f', '24', true, true, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('ttrembeyc', 'ssamarthc@aol.com', '1bNnW5YX', 'engineer clicks-and-mortar relationships', null, '12/13/1931', 'f', '109', false, false, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('sstanfordd', 'nbrendeld@spiegel.de', '0qnuVL8Aj', 'envisioneer sexy users', null, '07/01/1906', 'Polygender', '77', true, false, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('iyoudee', 'adrainse@goo.ne.jp', 'LOUT2zpl', 'reintermediate open-source methodologies', null, '09/24/1979', 'n', '78', true, false, true, false);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('jwarfieldf', 'mervinef@behance.net', 'HN9mhx', 'incubate robust channels', null, '04/30/1935', 'f', '29489', true, true, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('iodomg', 'bwashbrookg@bloglovin.com', 'ZdTpo2Atsf', 'benchmark collaborative content', null, '03/16/2013', 'Bigender', '504', false, false, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('sphonixh', 'sduchesneh@moonfruit.com', 'J4GQnyXC8C', 'aggregate revolutionary bandwidth', null, '06/05/1954', 'Genderfluid', '2387', false, true, true, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('fosbidstoni', 'tdoddemeedei@umn.edu', '5PwEC1GpWoU', 'engage user-centric web-readiness', null, '10/08/2007', 'Agender', '28422', true, false, false, true);
insert into users (username, email, password, description, photo, birthdate, gender, reputation, is_moderator, is_banned, is_partner, is_deleted) values ('bturrillj', 'jwarlowj@g.co', '3NRCEXNardY', 'enhance frictionless e-business', null, '11/11/1924', 'n', '91276', false, true, true, false);


insert into follow (follower_id, users_id) values (6, 7);
insert into follow (follower_id, users_id) values (4, 10);
insert into follow (follower_id, users_id) values (9, 12);
insert into follow (follower_id, users_id) values (7, 9);
insert into follow (follower_id, users_id) values (10, 13);
insert into follow (follower_id, users_id) values (7, 12);
insert into follow (follower_id, users_id) values (1, 3);
insert into follow (follower_id, users_id) values (10, 3);
insert into follow (follower_id, users_id) values (2, 8);
insert into follow (follower_id, users_id) values (8, 15);
insert into follow (follower_id, users_id) values (9, 7);
insert into follow (follower_id, users_id) values (6, 8);
insert into follow (follower_id, users_id) values (20, 17);
insert into follow (follower_id, users_id) values (18, 14);
insert into follow (follower_id, users_id) values (10, 19);
insert into follow (follower_id, users_id) values (4, 2);
insert into follow (follower_id, users_id) values (11, 10);
insert into follow (follower_id, users_id) values (6, 16);
insert into follow (follower_id, users_id) values (11, 1);
insert into follow (follower_id, users_id) values (19, 20);